### ISSUE TITLE
Form doesn't show if value is empty

### ISSUE THREAD

**Issue by zebra964** [formr/formr.github.io#4]
Hi thank you for this class it looks nice.
However I'm don't understand this bit (line 2807): 
    protected function _create_input($data)
    {
        if (!isset($_POST)) {
            if (empty($data['value'])) {
                return false;
            }
        }

why it should return false if the value is empty and there's no post? When I to create a from it show well when the value already exists but I can't display a new form to fill with no data yet. If I just remove the return false line then it works

**Comment by timgavin** [comment]
This is the repo for Formr's documentation. Please open this issue under the [Formr code repo](https://github.com/formr/formr), and include a sample of your code so I can see how you're using it.
